apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: antonio-casa-tls
spec:
  secretName: antonio-casa
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: antonio.casa
  dnsNames:
    - antonio.casa
    - www.antonio.casa